//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GhanaWoods.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LearnTabMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LearnTabMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GhanaWoods.Resources.Languages.LearnTabMain", typeof(LearnTabMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to banded apotracheal parenchyma.
        /// </summary>
        internal static string BAP {
            get {
                return ResourceManager.GetString("BAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct!.
        /// </summary>
        internal static string Correct_ {
            get {
                return ResourceManager.GetString("Correct!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answers selected:.
        /// </summary>
        internal static string Correct_answers_selected_ {
            get {
                return ResourceManager.GetString("Correct answers selected:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eschweilera.
        /// </summary>
        internal static string Eschweilera {
            get {
                return ResourceManager.GetString("Eschweilera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eucalyptus.
        /// </summary>
        internal static string Eucalyptus {
            get {
                return ResourceManager.GetString("Eucalyptus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardwood .
        /// </summary>
        internal static string Hardwood {
            get {
                return ResourceManager.GetString("Hardwood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardwood: .
        /// </summary>
        internal static string Hardwood_ {
            get {
                return ResourceManager.GetString("Hardwood:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardwoods.
        /// </summary>
        internal static string Hardwoods {
            get {
                return ResourceManager.GetString("Hardwoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distinct growth ring boundaries.
        /// </summary>
        internal static string HW1 {
            get {
                return ResourceManager.GetString("HW1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vessels in radial multiples of 4 or more commonly.
        /// </summary>
        internal static string HW10 {
            get {
                return ResourceManager.GetString("HW10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vessel clusters commonly.
        /// </summary>
        internal static string HW11 {
            get {
                return ResourceManager.GetString("HW11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to few rays.
        /// </summary>
        internal static string HW114 {
            get {
                return ResourceManager.GetString("HW114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average ray abundance.
        /// </summary>
        internal static string HW115 {
            get {
                return ResourceManager.GetString("HW115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numerous rays.
        /// </summary>
        internal static string HW116 {
            get {
                return ResourceManager.GetString("HW116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indistinct or absent growth ring boundaries.
        /// </summary>
        internal static string HW2 {
            get {
                return ResourceManager.GetString("HW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ring-porosity.
        /// </summary>
        internal static string HW3 {
            get {
                return ResourceManager.GetString("HW3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semi-ring-porosity.
        /// </summary>
        internal static string HW4 {
            get {
                return ResourceManager.GetString("HW4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diffuse-porosity.
        /// </summary>
        internal static string HW5 {
            get {
                return ResourceManager.GetString("HW5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tyloses commonly.
        /// </summary>
        internal static string HW56 {
            get {
                return ResourceManager.GetString("HW56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gums and other deposits in heartwood vessels.
        /// </summary>
        internal static string HW58 {
            get {
                return ResourceManager.GetString("HW58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vessels in tangential bands.
        /// </summary>
        internal static string HW6 {
            get {
                return ResourceManager.GetString("HW6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vessels in diagonal and/or radial pattern.
        /// </summary>
        internal static string HW7 {
            get {
                return ResourceManager.GetString("HW7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apotracheal diffuse parenchyma.
        /// </summary>
        internal static string HW76 {
            get {
                return ResourceManager.GetString("HW76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apotracheal diffuse-in-aggregate parenchyma.
        /// </summary>
        internal static string HW77 {
            get {
                return ResourceManager.GetString("HW77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scanty paratracheal parenchyma.
        /// </summary>
        internal static string HW78 {
            get {
                return ResourceManager.GetString("HW78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paratracheal vasicentric parenchyma.
        /// </summary>
        internal static string HW79 {
            get {
                return ResourceManager.GetString("HW79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vessels in dendritic pattern.
        /// </summary>
        internal static string HW8 {
            get {
                return ResourceManager.GetString("HW8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paratracheal aliform parenchyma.
        /// </summary>
        internal static string HW80 {
            get {
                return ResourceManager.GetString("HW80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paratracheal lozenge-aliform parenchyma.
        /// </summary>
        internal static string HW81 {
            get {
                return ResourceManager.GetString("HW81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paratracheal winged-aliform parenchyma.
        /// </summary>
        internal static string HW82 {
            get {
                return ResourceManager.GetString("HW82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paratracheal confluent parenchyma.
        /// </summary>
        internal static string HW83 {
            get {
                return ResourceManager.GetString("HW83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unilateral paratracheal parenchyma.
        /// </summary>
        internal static string HW84 {
            get {
                return ResourceManager.GetString("HW84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parenchyma in wide bands.
        /// </summary>
        internal static string HW85 {
            get {
                return ResourceManager.GetString("HW85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parenchyma in narrow bands or lines.
        /// </summary>
        internal static string HW86 {
            get {
                return ResourceManager.GetString("HW86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parenchyma in reticulate bands.
        /// </summary>
        internal static string HW87 {
            get {
                return ResourceManager.GetString("HW87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to marginal parenchyma.
        /// </summary>
        internal static string HW89 {
            get {
                return ResourceManager.GetString("HW89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vessels exclusively solitary (90% or more).
        /// </summary>
        internal static string HW9 {
            get {
                return ResourceManager.GetString("HW9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to narrow rays.
        /// </summary>
        internal static string HW96 {
            get {
                return ResourceManager.GetString("HW96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium to narrow rays.
        /// </summary>
        internal static string HW97 {
            get {
                return ResourceManager.GetString("HW97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wide rays.
        /// </summary>
        internal static string HW98 {
            get {
                return ResourceManager.GetString("HW98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to very wide rays.
        /// </summary>
        internal static string HW99 {
            get {
                return ResourceManager.GetString("HW99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth Ring Boundaries.
        /// </summary>
        internal static string HWcat1 {
            get {
                return ResourceManager.GetString("HWcat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banded Parenchyma.
        /// </summary>
        internal static string HWcat10 {
            get {
                return ResourceManager.GetString("HWcat10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porosity.
        /// </summary>
        internal static string HWcat2 {
            get {
                return ResourceManager.GetString("HWcat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel Arrangement.
        /// </summary>
        internal static string HWcat3 {
            get {
                return ResourceManager.GetString("HWcat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel Groupings.
        /// </summary>
        internal static string HWcat4 {
            get {
                return ResourceManager.GetString("HWcat4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyloses and Deposits in Vessels.
        /// </summary>
        internal static string HWcat5 {
            get {
                return ResourceManager.GetString("HWcat5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ray Width.
        /// </summary>
        internal static string HWcat6 {
            get {
                return ResourceManager.GetString("HWcat6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ray Abundance.
        /// </summary>
        internal static string HWcat7 {
            get {
                return ResourceManager.GetString("HWcat7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apotracheal Axial Parenchyma.
        /// </summary>
        internal static string HWcat8 {
            get {
                return ResourceManager.GetString("HWcat8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paratracheal Axial Parenchyma.
        /// </summary>
        internal static string HWcat9 {
            get {
                return ResourceManager.GetString("HWcat9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vessels in radial multiples of 4 or more common.
        /// </summary>
        internal static string HWf10 {
            get {
                return ResourceManager.GetString("HWf10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vessel clusters common.
        /// </summary>
        internal static string HWf11 {
            get {
                return ResourceManager.GetString("HWf11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ring-porous.
        /// </summary>
        internal static string HWf3 {
            get {
                return ResourceManager.GetString("HWf3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semi-ring-porous.
        /// </summary>
        internal static string HWf4 {
            get {
                return ResourceManager.GetString("HWf4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diffuse-porous.
        /// </summary>
        internal static string HWf5 {
            get {
                return ResourceManager.GetString("HWf5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tyloses common.
        /// </summary>
        internal static string HWf56 {
            get {
                return ResourceManager.GetString("HWf56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect..
        /// </summary>
        internal static string Incorrect_ {
            get {
                return ResourceManager.GetString("Incorrect.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect selections:.
        /// </summary>
        internal static string Incorrect_selections_ {
            get {
                return ResourceManager.GetString("Incorrect selections:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz.
        /// </summary>
        internal static string learnFC {
            get {
                return ResourceManager.GetString("learnFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed: .
        /// </summary>
        internal static string Missed_ {
            get {
                return ResourceManager.GetString("Missed:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Features Page.
        /// </summary>
        internal static string Open_Features_Page {
            get {
                return ResourceManager.GetString("Open Features Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Species Page.
        /// </summary>
        internal static string Open_Species_Page {
            get {
                return ResourceManager.GetString("Open Species Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string qMark {
            get {
                return ResourceManager.GetString("qMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result:.
        /// </summary>
        internal static string Result_ {
            get {
                return ResourceManager.GetString("Result:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the anatomical features present in the following group: .
        /// </summary>
        internal static string sAFg {
            get {
                return ResourceManager.GetString("sAFg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the anatomical features present in the following species: .
        /// </summary>
        internal static string sAFs {
            get {
                return ResourceManager.GetString("sAFs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected: .
        /// </summary>
        internal static string Selected_ {
            get {
                return ResourceManager.GetString("Selected:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Softwood .
        /// </summary>
        internal static string Softwood {
            get {
                return ResourceManager.GetString("Softwood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Softwood: .
        /// </summary>
        internal static string Softwood_ {
            get {
                return ResourceManager.GetString("Softwood:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Softwoods.
        /// </summary>
        internal static string Softwoods {
            get {
                return ResourceManager.GetString("Softwoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species.
        /// </summary>
        internal static string Species {
            get {
                return ResourceManager.GetString("Species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  spp..
        /// </summary>
        internal static string spp_ {
            get {
                return ResourceManager.GetString("spp.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to axial resin canals.
        /// </summary>
        internal static string SW109 {
            get {
                return ResourceManager.GetString("SW109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to traumatic resin canals.
        /// </summary>
        internal static string SW111 {
            get {
                return ResourceManager.GetString("SW111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distinct growth ring boundaries.
        /// </summary>
        internal static string SW40 {
            get {
                return ResourceManager.GetString("SW40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indistinct or absent growth ring boundaries.
        /// </summary>
        internal static string SW41 {
            get {
                return ResourceManager.GetString("SW41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an abrupt transition from earlywood to latewood.
        /// </summary>
        internal static string SW42 {
            get {
                return ResourceManager.GetString("SW42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a gradual transition from earlywood to latewood.
        /// </summary>
        internal static string SW43 {
            get {
                return ResourceManager.GetString("SW43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to axial parenchyma.
        /// </summary>
        internal static string SW72 {
            get {
                return ResourceManager.GetString("SW72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diffuse parenchyma.
        /// </summary>
        internal static string SW73 {
            get {
                return ResourceManager.GetString("SW73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangentially zonate parenchyma.
        /// </summary>
        internal static string SW74 {
            get {
                return ResourceManager.GetString("SW74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to marginal parenchyma.
        /// </summary>
        internal static string SW75 {
            get {
                return ResourceManager.GetString("SW75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth Ring Boundaries.
        /// </summary>
        internal static string SWcat1 {
            get {
                return ResourceManager.GetString("SWcat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth Ring Transitions.
        /// </summary>
        internal static string SWcat2 {
            get {
                return ResourceManager.GetString("SWcat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axial Parenchyma.
        /// </summary>
        internal static string SWcat3 {
            get {
                return ResourceManager.GetString("SWcat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intercellular Canals.
        /// </summary>
        internal static string SWcat4 {
            get {
                return ResourceManager.GetString("SWcat4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which group displays vasicentric parenchyma?.
        /// </summary>
        internal static string vasicentric_parenchyma {
            get {
                return ResourceManager.GetString("vasicentric parenchyma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vasicentric parenchyma.
        /// </summary>
        internal static string VP {
            get {
                return ResourceManager.GetString("VP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well done! Correct answers selected:.
        /// </summary>
        internal static string Well_done__Correct_answers_selected_ {
            get {
                return ResourceManager.GetString("Well done! Correct answers selected:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which group displays .
        /// </summary>
        internal static string wGD {
            get {
                return ResourceManager.GetString("wGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which species displays .
        /// </summary>
        internal static string wSD {
            get {
                return ResourceManager.GetString("wSD", resourceCulture);
            }
        }
    }
}
