//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GhanaWoods.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReferenceTabGroup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReferenceTabGroup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GhanaWoods.Resources.Languages.ReferenceTabGroup", typeof(ReferenceTabGroup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional comments.
        /// </summary>
        internal static string Additional_comments {
            get {
                return ResourceManager.GetString("Additional comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  • .
        /// </summary>
        internal static string dot {
            get {
                return ResourceManager.GetString("dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family: .
        /// </summary>
        internal static string Family_ {
            get {
                return ResourceManager.GetString("Family:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other characters.
        /// </summary>
        internal static string Other_characters {
            get {
                return ResourceManager.GetString("Other characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other characters: .
        /// </summary>
        internal static string Other_characters_ {
            get {
                return ResourceManager.GetString("Other characters:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parenchyma: .
        /// </summary>
        internal static string Parenchyma_ {
            get {
                return ResourceManager.GetString("Parenchyma:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porosity: .
        /// </summary>
        internal static string Porosity_ {
            get {
                return ResourceManager.GetString("Porosity:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached a potential match for your identification..
        /// </summary>
        internal static string potential_match {
            get {
                return ResourceManager.GetString("potential match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rays: .
        /// </summary>
        internal static string Rays_ {
            get {
                return ResourceManager.GetString("Rays:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string referenceFC {
            get {
                return ResourceManager.GetString("referenceFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember to compare your specimen with the images and information on this page, notably those under Similar Woods, before confirming your decision..
        /// </summary>
        internal static string Remember_to_compare {
            get {
                return ResourceManager.GetString("Remember to compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        internal static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar woods.
        /// </summary>
        internal static string Similar_woods {
            get {
                return ResourceManager.GetString("Similar woods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species Group.
        /// </summary>
        internal static string Species_Group {
            get {
                return ResourceManager.GetString("Species Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  spp..
        /// </summary>
        internal static string spp_ {
            get {
                return ResourceManager.GetString("spp.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of characters.
        /// </summary>
        internal static string Summary_of_characters {
            get {
                return ResourceManager.GetString("Summary of characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangential.
        /// </summary>
        internal static string Tangential {
            get {
                return ResourceManager.GetString("Tangential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangential: .
        /// </summary>
        internal static string Tangential_ {
            get {
                return ResourceManager.GetString("Tangential:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transverse.
        /// </summary>
        internal static string Transverse {
            get {
                return ResourceManager.GetString("Transverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transverse: .
        /// </summary>
        internal static string Transverse_ {
            get {
                return ResourceManager.GetString("Transverse:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessels: .
        /// </summary>
        internal static string Vessels_ {
            get {
                return ResourceManager.GetString("Vessels:", resourceCulture);
            }
        }
    }
}
