//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GhanaWoods.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReferenceTabMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReferenceTabMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GhanaWoods.Resources.Languages.ReferenceTabMain", typeof(ReferenceTabMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species.
        /// </summary>
        internal static string referenceFC {
            get {
                return ResourceManager.GetString("referenceFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abarema.
        /// </summary>
        internal static string spGrName1 {
            get {
                return ResourceManager.GetString("spGrName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avicennia.
        /// </summary>
        internal static string spGrName10 {
            get {
                return ResourceManager.GetString("spGrName10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azadirachta indica.
        /// </summary>
        internal static string spGrName11 {
            get {
                return ResourceManager.GetString("spGrName11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bactris gasipaes.
        /// </summary>
        internal static string spGrName12 {
            get {
                return ResourceManager.GetString("spGrName12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bambusa vulgaris.
        /// </summary>
        internal static string spGrName13 {
            get {
                return ResourceManager.GetString("spGrName13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abies.
        /// </summary>
        internal static string spGrName2 {
            get {
                return ResourceManager.GetString("spGrName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acacia.
        /// </summary>
        internal static string spGrName3 {
            get {
                return ResourceManager.GetString("spGrName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albizia.
        /// </summary>
        internal static string spGrName4 {
            get {
                return ResourceManager.GetString("spGrName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alchornea latifolia.
        /// </summary>
        internal static string spGrName5 {
            get {
                return ResourceManager.GetString("spGrName5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anacardium.
        /// </summary>
        internal static string spGrName6 {
            get {
                return ResourceManager.GetString("spGrName6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andira.
        /// </summary>
        internal static string spGrName7 {
            get {
                return ResourceManager.GetString("spGrName7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspidosperma.
        /// </summary>
        internal static string spGrName8 {
            get {
                return ResourceManager.GetString("spGrName8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronium.
        /// </summary>
        internal static string spGrName9 {
            get {
                return ResourceManager.GetString("spGrName9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. alexandri; A. glauca; A. idiopoda.
        /// </summary>
        internal static string spGrSpecies1 {
            get {
                return ResourceManager.GetString("spGrSpecies1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. bicolor (A. tonduzii); A. germinans; A. marina (A. alba).
        /// </summary>
        internal static string spGrSpecies10 {
            get {
                return ResourceManager.GetString("spGrSpecies10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string spGrSpecies11 {
            get {
                return ResourceManager.GetString("spGrSpecies11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string spGrSpecies12 {
            get {
                return ResourceManager.GetString("spGrSpecies12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string spGrSpecies13 {
            get {
                return ResourceManager.GetString("spGrSpecies13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. guatemalensis; A. religiosa.
        /// </summary>
        internal static string spGrSpecies2 {
            get {
                return ResourceManager.GetString("spGrSpecies2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. angustissima (Acaciella angustissima); A. choriophylla (Vachellia choriophylla); A. farnesiana (Vachellia farnesiana); A. macracantha (Vachellia macracantha); A. mangium; A. pennatula (Vachellia pennatula).
        /// </summary>
        internal static string spGrSpecies3 {
            get {
                return ResourceManager.GetString("spGrSpecies3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. adinocephala; A. berteroana; A. cubana; A. guachapele (Pseudosamanea guachapele); A. niopoides (A. caribaea); A. procera; A. saman (Samanea saman).
        /// </summary>
        internal static string spGrSpecies4 {
            get {
                return ResourceManager.GetString("spGrSpecies4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string spGrSpecies5 {
            get {
                return ResourceManager.GetString("spGrSpecies5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. excelsum; A. occidentale.
        /// </summary>
        internal static string spGrSpecies6 {
            get {
                return ResourceManager.GetString("spGrSpecies6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. galeottiana; A. inermis.
        /// </summary>
        internal static string spGrSpecies7 {
            get {
                return ResourceManager.GetString("spGrSpecies7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. desmanthum (A. cruentum); A. megalocarpon.
        /// </summary>
        internal static string spGrSpecies8 {
            get {
                return ResourceManager.GetString("spGrSpecies8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. fraxinifolium; A. graveolens.
        /// </summary>
        internal static string spGrSpecies9 {
            get {
                return ResourceManager.GetString("spGrSpecies9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  spp..
        /// </summary>
        internal static string spp_ {
            get {
                return ResourceManager.GetString("spp.", resourceCulture);
            }
        }
    }
}
