//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GhanaWoods.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsTab {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsTab() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GhanaWoods.Resources.Languages.SettingsTab", typeof(SettingsTab).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorblind mode: .
        /// </summary>
        internal static string Colorblind_mode_ {
            get {
                return ResourceManager.GetString("Colorblind mode:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors:
        ///&lt;Rafael Arévalo, Emmanuel Ebanyenle, Alberta Asi Ebeheakey, Kofi Abban Bonsu, Ophilious Lambog, Richard Soares, Alex C. Wiedenhoeft, Kyatt Spessert, Frank Owens, Adriana Costa,&gt; and &lt;Rubin Shmulsky&gt;.
        /// </summary>
        internal static string Credits_description {
            get {
                return ResourceManager.GetString("Credits description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///This app is a reimagination of the manual &quot;Field Identification Manual for Ghanaian Timbers&quot; published by the USDA Forest Products Laboratory.
        ///
        ///Arevalo, Rafael; Ebanyenle, Emmanuel; Ebeheakey, Alberta Asi; Bonsu, Kofi Abban; Lambog, Ophilious; Soares, Richard; Wiedenhoeft, Alex C. 2020. [Field identification manual for Ghanaian timbers.] FPL Gen Tech. Rep. FPL-GTR-277. Madison, WI: U.S. Department of Agriculture, Forest Service, Forest Products Laboratory. 130 p. ^https://www.fpl.fs.usda.gov/documnts/fp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Credits_description_cont {
            get {
                return ResourceManager.GetString("Credits description cont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///This app is a reimagination of the field manual &quot;Identification of Central American, Mexican, and Caribbean Woods&quot; by Drs. Rafael Arévalo and Alex Wiedenhoeft.
        ///
        ///Arévalo, Rafael; Wiedenhoeft, Alex C. 2022. [Identificación de las Maderas de Centroamérica, México y el Caribe—Identification of Central American, Mexican, and Caribbean Woods.] General Technical Report FPL-GTR-293. Madison, WI: U.S. Department of Agriculture, Forest Service, Forest Products Laboratory. 376 p. ^https://doi.org/10.2737/FPL-GTR-2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Credits_description_contOG {
            get {
                return ResourceManager.GetString("Credits description contOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///This app is a reimagination of the manual &quot;Field Identification Manual for Ghanaian Timbers&quot; published by the USDA Forest Products Laboratory.
        ///
        ///Arevalo, Rafael; Ebanyenle, Emmanuel; Ebeheakey, Alberta Asi; Bonsu, Kofi Abban; Lambog, Ophilious; Soares, Richard; Wiedenhoeft, Alex C. 2020. [Field identification manual for Ghanaian timbers.] FPL Gen Tech. Rep. FPL-GTR-277. Madison, WI: U.S. Department of Agriculture, Forest Service, Forest Products Laboratory. 130 p..
        /// </summary>
        internal static string Credits_description_iOS {
            get {
                return ResourceManager.GetString("Credits description iOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^https://www.fpl.fs.usda.gov/documnts/fplgtr/fpl_gtr277.pdf|.
        /// </summary>
        internal static string Credits_description_iOS1 {
            get {
                return ResourceManager.GetString("Credits description iOS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^https://doi.org/10.2737/FPL-GTR-293|.
        /// </summary>
        internal static string Credits_description_iOS1OG {
            get {
                return ResourceManager.GetString("Credits description iOS1OG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Image credits:
        ///Dominique Belcher (2020)
        ///
        ///This material is based upon work that is supported by the National Institute of Food and Agriculture, U.S. Department of Agriculture, McIntire Stennis project under accession number 7004014.
        ///
        ///This publication is a contribution of the Forest and Wildlife Research Center, Mississippi State University..
        /// </summary>
        internal static string Credits_description_iOS2 {
            get {
                return ResourceManager.GetString("Credits description iOS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Image credits:
        ///Dominique Belcher (2020)
        ///Lencer (2007) “Vorlage Karibik/Mittelamerika, Blank Map Caribbean Sea,”.
        /// </summary>
        internal static string Credits_description_iOS2OG {
            get {
                return ResourceManager.GetString("Credits description iOS2OG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^https://commons.wikimedia.org/wiki/File:Caribbean_Sea_and_West_Indies.png|.
        /// </summary>
        internal static string Credits_description_iOS3OG {
            get {
                return ResourceManager.GetString("Credits description iOS3OG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///This material is based upon work that is supported by the National Institute of Food and Agriculture, U.S. Department of Agriculture, McIntire Stennis project under accession number 7004014.
        ///
        ///This publication is a contribution of the Forest and Wildlife Research Center, Mississippi State University..
        /// </summary>
        internal static string Credits_description_iOS4OG {
            get {
                return ResourceManager.GetString("Credits description iOS4OG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///This app is a reimagination of the field manual &quot;Identification of Central American, Mexican, and Caribbean Woods&quot; by Drs. Rafael Arévalo and Alex Wiedenhoeft.
        ///
        ///Arévalo, Rafael; Wiedenhoeft, Alex C. 2022. [Identificación de las Maderas de Centroamérica, México y el Caribe—Identification of Central American, Mexican, and Caribbean Woods.] General Technical Report FPL-GTR-293. Madison, WI: U.S. Department of Agriculture, Forest Service, Forest Products Laboratory. 376 p. .
        /// </summary>
        internal static string Credits_description_iOSOG {
            get {
                return ResourceManager.GetString("Credits description iOSOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors:
        ///&lt;Alex C. Wiedenhoeft, Rafael Arévalo, Kyatt Spessert, Frank Owens, Adriana Costa,&gt; and &lt;Rubin Shmulsky&gt;.
        /// </summary>
        internal static string Credits_descriptionOG {
            get {
                return ResourceManager.GetString("Credits descriptionOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The views and opinions expressed herein are strictly those of the authors. The contents of this app have not been reviewed or approved by Mississippi State University or the USDA Forest Service..
        /// </summary>
        internal static string Credits_disclaimer {
            get {
                return ResourceManager.GetString("Credits disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition hyperlinks: .
        /// </summary>
        internal static string Definition_hyperlinks_ {
            get {
                return ResourceManager.GetString("Definition hyperlinks:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert mode: .
        /// </summary>
        internal static string Expert_mode_ {
            get {
                return ResourceManager.GetString("Expert mode:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size: .
        /// </summary>
        internal static string Font_size_ {
            get {
                return ResourceManager.GetString("Font size:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key scroll animation: .
        /// </summary>
        internal static string I_D__scroll_animation_ {
            get {
                return ResourceManager.GetString("I.D. scroll animation:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string idC {
            get {
                return ResourceManager.GetString("idC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization.
        /// </summary>
        internal static string Initialization {
            get {
                return ResourceManager.GetString("Initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: .
        /// </summary>
        internal static string Language_ {
            get {
                return ResourceManager.GetString("Language:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch page: .
        /// </summary>
        internal static string Launch_page_ {
            get {
                return ResourceManager.GetString("Launch page:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz.
        /// </summary>
        internal static string learnFC {
            get {
                return ResourceManager.GetString("learnFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading_assets {
            get {
                return ResourceManager.GetString("Loading assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species.
        /// </summary>
        internal static string referenceFC {
            get {
                return ResourceManager.GetString("referenceFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settingsFC {
            get {
                return ResourceManager.GetString("settingsFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        internal static string settingsLC {
            get {
                return ResourceManager.GetString("settingsLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study hyperlinks: .
        /// </summary>
        internal static string Study_hyperlinks_ {
            get {
                return ResourceManager.GetString("Study hyperlinks:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string studyFC {
            get {
                return ResourceManager.GetString("studyFC", resourceCulture);
            }
        }
    }
}
