//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GhanaWoods.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StudyTab1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StudyTab1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GhanaWoods.Resources.Languages.StudyTab1", typeof(StudyTab1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abrupt transition.
        /// </summary>
        internal static string abrupt_transition {
            get {
                return ResourceManager.GetString("abrupt transition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aliform parenchyma.
        /// </summary>
        internal static string aliform_parenchyma {
            get {
                return ResourceManager.GetString("aliform parenchyma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apotracheal parenchyma.
        /// </summary>
        internal static string apotracheal_parenchyma {
            get {
                return ResourceManager.GetString("apotracheal parenchyma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to axial system.
        /// </summary>
        internal static string axial_system {
            get {
                return ResourceManager.GetString("axial system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to banded parenchyma.
        /// </summary>
        internal static string banded_parenchyma {
            get {
                return ResourceManager.GetString("banded parenchyma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cells.
        /// </summary>
        internal static string cells {
            get {
                return ResourceManager.GetString("cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch..
        /// </summary>
        internal static string Ch_ {
            get {
                return ResourceManager.GetString("Ch.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string Ch8_I {
            get {
                return ResourceManager.GetString("Ch8 I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This book compiles wood identification features of selected species in Ghana to assist in their identification. It also includes tree identification features; notes on ecology, silviculture, and ethnobotany; and uses of the timber species..
        /// </summary>
        internal static string Ch8R1d {
            get {
                return ResourceManager.GetString("Ch8R1d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Oteng-Amoako, A.A.&gt; 2006. [100 Tropical African Timber Trees From Ghana: Tree Description and Wood Identification with Notes on Distribution, Ecology, Silviculture, Ethnobotany and Wood Uses]. Kumasi, Ghana: Forest Research Institute of Ghana..
        /// </summary>
        internal static string Ch8R1r {
            get {
                return ResourceManager.GetString("Ch8R1r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 Tropical African Timber Trees.
        /// </summary>
        internal static string Ch8R1t {
            get {
                return ResourceManager.GetString("Ch8R1t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a tremendously useful resource for wood identification in the laboratory, with a distinct emphasis on light microscopic identification. It incorporates a (usually) complete anatomical characterization of each species in the database, it allows rapid searching, and many of the species it covers are illustrated with a variety of photographs. Despite the emphasis on microscopy, many of the species in the database have one or more images similar in magnification to those in this manual. InsideWood is be [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ch8R2d {
            get {
                return ResourceManager.GetString("Ch8R2d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;InsideWood.&gt; 2004 onwards. Published on the internet. North Carolina State University, Raleigh, NC. (^https://insidewood.lib.ncsu.edu/search?0|).
        /// </summary>
        internal static string Ch8R2r {
            get {
                return ResourceManager.GetString("Ch8R2r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;InsideWood.&gt; 2004 onwards. Published on the internet. North Carolina State University, Raleigh, NC..
        /// </summary>
        internal static string Ch8R2riOS {
            get {
                return ResourceManager.GetString("Ch8R2riOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^https://insidewood.lib.ncsu.edu/search?0|).
        /// </summary>
        internal static string Ch8R2riOS1 {
            get {
                return ResourceManager.GetString("Ch8R2riOS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsideWood.
        /// </summary>
        internal static string Ch8R2t {
            get {
                return ResourceManager.GetString("Ch8R2t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These books provide basic information on the structure, properties, and identification of woods, with a greater emphasis on North American species. The information is clearly presented with high-quality illustrations but emphasizes microscopic rather than hand lens observation of wood for identification..
        /// </summary>
        internal static string Ch8R3d {
            get {
                return ResourceManager.GetString("Ch8R3d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Hoadley, R.B.&gt; 2000. [Understanding Wood: A Craftsman’s Guide to Wood Technology.] 2nd Ed. Newtown, CT: Taunton Press.
        ///&lt;Hoadley, R.B.&gt; 1990. [Identifying Wood: Accurate Results with Simple Tools.] Newtown, CT: Taunton Press..
        /// </summary>
        internal static string Ch8R3r {
            get {
                return ResourceManager.GetString("Ch8R3r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoadley’s books.
        /// </summary>
        internal static string Ch8R3t {
            get {
                return ResourceManager.GetString("Ch8R3t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a famous but out-of-print college textbook for understanding many aspects of wood technology, including detailed information on wood identification of North American species. The identification keys in the book are of questionable consistency and reliability. Despite the comparative weakness of the keys themselves, the earlier chapters reviewing the scientific literature in wood technology are useful and relatively up-to-date as of the year of publication..
        /// </summary>
        internal static string Ch8R4d {
            get {
                return ResourceManager.GetString("Ch8R4d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Panshin, A.J.; deZeeuw, C.&gt; 1980. [Textbook of Wood Technology]. 4th ed. New York: McGraw-Hill..
        /// </summary>
        internal static string Ch8R4r {
            get {
                return ResourceManager.GetString("Ch8R4r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textbook of Wood Technology.
        /// </summary>
        internal static string Ch8R4t {
            get {
                return ResourceManager.GetString("Ch8R4t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n using the key and the species description pages, we are sure you noticed that identification of an exact species is rarely possible. This is due in part to the nature of the tools we are using in this manual. A hand lens is a powerful tool for wood identification, but it is not the most powerful method for identification based on anatomical characteristics. The greatest power in wood identification comes with the use of light microscopy in a laboratory with a scientifically valid reference collection (mor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ch8S1 {
            get {
                return ResourceManager.GetString("Ch8S1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field identification of wood and wood products is the first step in the process of ensuring legal trade and wise use of forest resources, but it is not the only step. Within each country, there is a critical need for one or more scientific centers that specialize in the forensic identification of wood. That is, places that have the resources to provide identifications that meet scientific standards sufficient to be used as evidence in a trial. If stopping a shipment is the first and necessary part of the pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ch8S2 {
            get {
                return ResourceManager.GetString("Ch8S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimately, scientific wood identification depends on a valid set of known specimens with which unknown specimens can be compared. Most of the specimens shown in this manual were taken directly from institutional wood collections or were compared with specimens in those collections and deemed to be valid specimens. In Ghana, the wood collection of record is maintained by CSIR-FORIG in Kumasi. The need for a large scientific collection at the national level does not mean that you should not have your own sma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ch8S3 {
            get {
                return ResourceManager.GetString("Ch8S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many wood identification references are available in addition to this manual. Many of them are written for professional wood anatomists with specific emphasis on the microscopic identification of wood. These resources, though parts will exceed your current knowledge, may nonetheless prove useful in your work. Other references will be more appropriate for your use as you develop your skills in wood identification. It is important to keep in mind that not all references are of the same quality; some reference [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ch8S4 {
            get {
                return ResourceManager.GetString("Ch8S4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.1 The limits of wood identification.
        /// </summary>
        internal static string Ch8T1 {
            get {
                return ResourceManager.GetString("Ch8T1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.2 The need for scientific forensic expertise to combat illegal logging.
        /// </summary>
        internal static string Ch8T2 {
            get {
                return ResourceManager.GetString("Ch8T2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.3 Building a reference wood collection.
        /// </summary>
        internal static string Ch8T3 {
            get {
                return ResourceManager.GetString("Ch8T3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.4 Additional wood identification information.
        /// </summary>
        internal static string Ch8T4 {
            get {
                return ResourceManager.GetString("Ch8T4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter.
        /// </summary>
        internal static string Chapter {
            get {
                return ResourceManager.GetString("Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information about wood identification.
        /// </summary>
        internal static string Chapter_8_Title {
            get {
                return ResourceManager.GetString("Chapter 8 Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clusters (vessel arrangement).
        /// </summary>
        internal static string clusters__vessel_arrangement_ {
            get {
                return ResourceManager.GetString("clusters (vessel arrangement)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color.
        /// </summary>
        internal static string color {
            get {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confluent parenchyma.
        /// </summary>
        internal static string confluent_parenchyma {
            get {
                return ResourceManager.GetString("confluent parenchyma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dendritic (vessel arrangement).
        /// </summary>
        internal static string dendritic__vessel_arrangement_ {
            get {
                return ResourceManager.GetString("dendritic (vessel arrangement)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to density.
        /// </summary>
        internal static string density {
            get {
                return ResourceManager.GetString("density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diffuse (parenchyma).
        /// </summary>
        internal static string diffuse__parenchyma_ {
            get {
                return ResourceManager.GetString("diffuse (parenchyma)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diffuse-in-aggregates parenchyma.
        /// </summary>
        internal static string diffuse_in_aggregates_parenchyma {
            get {
                return ResourceManager.GetString("diffuse-in-aggregates parenchyma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diffuse-porous.
        /// </summary>
        internal static string diffuse_porous {
            get {
                return ResourceManager.GetString("diffuse-porous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to earlywood.
        /// </summary>
        internal static string earlywood {
            get {
                return ResourceManager.GetString("earlywood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to echelon (vessel arrangement).
        /// </summary>
        internal static string echelon__vessel_arrangement_ {
            get {
                return ResourceManager.GetString("echelon (vessel arrangement)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fibers.
        /// </summary>
        internal static string fibers {
            get {
                return ResourceManager.GetString("fibers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fig..
        /// </summary>
        internal static string Fig_ {
            get {
                return ResourceManager.GetString("Fig.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figure.
        /// </summary>
        internal static string Figure {
            get {
                return ResourceManager.GetString("Figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fluorescence.
        /// </summary>
        internal static string fluorescence {
            get {
                return ResourceManager.GetString("fluorescence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genus.
        /// </summary>
        internal static string genus {
            get {
                return ResourceManager.GetString("genus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gradual transition.
        /// </summary>
        internal static string gradual_transition {
            get {
                return ResourceManager.GetString("gradual transition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to growth rings.
        /// </summary>
        internal static string growth_rings {
            get {
                return ResourceManager.GetString("growth rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hardness.
        /// </summary>
        internal static string hardness {
            get {
                return ResourceManager.GetString("hardness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hardwood.
        /// </summary>
        internal static string hardwood {
            get {
                return ResourceManager.GetString("hardwood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heartwood.
        /// </summary>
        internal static string heartwood {
            get {
                return ResourceManager.GetString("heartwood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key.
        /// </summary>
        internal static string key {
            get {
                return ResourceManager.GetString("key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latewood.
        /// </summary>
        internal static string latewood {
            get {
                return ResourceManager.GetString("latewood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Name.
        /// </summary>
        internal static string Local_Name {
            get {
                return ResourceManager.GetString("Local Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lozenge aliform parenchyma.
        /// </summary>
        internal static string lozenge_aliform_parenchyma {
            get {
                return ResourceManager.GetString("lozenge aliform parenchyma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to luster.
        /// </summary>
        internal static string luster {
            get {
                return ResourceManager.GetString("luster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to marginal parenchyma.
        /// </summary>
        internal static string marginal_parenchyma {
            get {
                return ResourceManager.GetString("marginal parenchyma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multiples (vessel).
        /// </summary>
        internal static string multiples__vessel_ {
            get {
                return ResourceManager.GetString("multiples (vessel)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to odor.
        /// </summary>
        internal static string odor {
            get {
                return ResourceManager.GetString("odor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paratracheal.
        /// </summary>
        internal static string paratracheal {
            get {
                return ResourceManager.GetString("paratracheal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parenchyma (axial).
        /// </summary>
        internal static string parenchyma__axial_ {
            get {
                return ResourceManager.GetString("parenchyma (axial)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parenchyma (cell type).
        /// </summary>
        internal static string parenchyma__cell_type_ {
            get {
                return ResourceManager.GetString("parenchyma (cell type)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pith.
        /// </summary>
        internal static string pith {
            get {
                return ResourceManager.GetString("pith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pores (see vessels).
        /// </summary>
        internal static string pores__see_vessels_ {
            get {
                return ResourceManager.GetString("pores (see vessels)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radial canals.
        /// </summary>
        internal static string radial_canals {
            get {
                return ResourceManager.GetString("radial canals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radial plane of section.
        /// </summary>
        internal static string radial_plane_of_section {
            get {
                return ResourceManager.GetString("radial plane of section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radial system.
        /// </summary>
        internal static string radial_system {
            get {
                return ResourceManager.GetString("radial system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radially aligned (vessel arrangement).
        /// </summary>
        internal static string radially_aligned__vessel_arrangement_ {
            get {
                return ResourceManager.GetString("radially aligned (vessel arrangement)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rays.
        /// </summary>
        internal static string rays {
            get {
                return ResourceManager.GetString("rays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resin canals.
        /// </summary>
        internal static string resin_canals {
            get {
                return ResourceManager.GetString("resin canals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ring porous.
        /// </summary>
        internal static string ring_porous {
            get {
                return ResourceManager.GetString("ring porous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ripple marks (see storied rays).
        /// </summary>
        internal static string ripple_marks__see_storied_rays_ {
            get {
                return ResourceManager.GetString("ripple marks (see storied rays)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sapwood.
        /// </summary>
        internal static string sapwood {
            get {
                return ResourceManager.GetString("sapwood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific Names.
        /// </summary>
        internal static string Scientific_Names {
            get {
                return ResourceManager.GetString("Scientific Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semi-ring-porous.
        /// </summary>
        internal static string semi_ring_porous {
            get {
                return ResourceManager.GetString("semi-ring-porous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to softwood.
        /// </summary>
        internal static string softwood {
            get {
                return ResourceManager.GetString("softwood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solitary (vessels).
        /// </summary>
        internal static string solitary__vessels_ {
            get {
                return ResourceManager.GetString("solitary (vessels)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specific epithet.
        /// </summary>
        internal static string specific_epithet {
            get {
                return ResourceManager.GetString("specific epithet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to storied rays.
        /// </summary>
        internal static string storied_rays {
            get {
                return ResourceManager.GetString("storied rays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to systems (tissue).
        /// </summary>
        internal static string systems__tissue_ {
            get {
                return ResourceManager.GetString("systems (tissue)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangential plane of section.
        /// </summary>
        internal static string tangential_plane_of_section {
            get {
                return ResourceManager.GetString("tangential plane of section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        internal static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tracheids.
        /// </summary>
        internal static string tracheids {
            get {
                return ResourceManager.GetString("tracheids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Names.
        /// </summary>
        internal static string Trade_Names {
            get {
                return ResourceManager.GetString("Trade Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transverse plane of section.
        /// </summary>
        internal static string transverse_plane_of_section {
            get {
                return ResourceManager.GetString("transverse plane of section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tyloses.
        /// </summary>
        internal static string tyloses {
            get {
                return ResourceManager.GetString("tyloses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vasicentric parenchyma.
        /// </summary>
        internal static string vasicentric_parenchyma {
            get {
                return ResourceManager.GetString("vasicentric parenchyma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vessel arrangement.
        /// </summary>
        internal static string vessel_arrangement {
            get {
                return ResourceManager.GetString("vessel arrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vessels (or pores).
        /// </summary>
        internal static string vessels__or_pores_ {
            get {
                return ResourceManager.GetString("vessels (or pores)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to winged aliform parenchyma.
        /// </summary>
        internal static string winged_aliform_parenchyma {
            get {
                return ResourceManager.GetString("winged aliform parenchyma", resourceCulture);
            }
        }
    }
}
